-- curso de 1 semestre
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('LIBRAS', 'AV101', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Práticas de Ensino para a Educação Especial numa Perspectiva Inclusiva', 'AV102', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Currículos, didática e Práticas Avaliativas do Ensino e da Aprendizagem', 'AV103', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Política e Organização da Educação no Brasil', 'AV104', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Estudo das Relações Étnico-Raciais para o Ensino de História e Cultura Afro-brasileira, Africana e Indígena', 'AV104', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Psicologia da Educação e Teorias da Aprendizagem', 'AV105', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Estética e Filosofia da Arte', 'AV106', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Fundamentos da Linguagem Visual', 'AV107', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Tecnologias Digitais e Expressões Artísticas Visuais', 'AV108', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Arte Conceitual, Instalações e Arte Urbana', 'AV109', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Arte Brasileira na formação da Identidade Nacional', 'AV110', null, 1)
-- curso de 1 ano e meio
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Teoria e Fundamentos de Gestão', 'MR101', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Tecnologia da Informação', 'MR102', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Pensamento Critico e Comunicação', 'MR103', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Introdução à Contabilidade', 'MR104', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Matemática Aplicada', 'MR105', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Meio Ambiente e Sustentabilidade', 'MR106' null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Projeto Multidisciplinar – Introdução à Gestão', 'MR107', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Marketing', 'MR108', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Comportamento do Consumidor', 'MR109', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Ambiente Legal de Negócios', 'MR110', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Planejamento de Marketing', 'MR111', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Economia de Empresas', 'MR112', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Gestão de Projetos', 'MR113', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Projeto Multidisciplinar – Marketing', 'MR114', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Marketing Digital', 'MR201', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Fundamentos de E-commerce e E-business', 'MR202', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Ética, Cidadania e Responsabilidade Social', 'MR203', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Comunicação em Redes Sociais', 'MR204', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Plataforma de E-commerce', 'MR205', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('História e Cultura Afro-brasileira e Indígena', 'MR206', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Projeto Multidisciplinar – Comércio Eletrônico e Mídias Digitais', 'MR207', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Branding', 'MR301', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Publicidade, Propaganda e Design', 'MR302', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Probabilidade e Estatística', 'MR303', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Estratégias de Marketing', 'MR304', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Planejamento Estratégico de Vendas', 'MR305', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Empreendedorismo', 'MR306', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Projeto Multidisciplinar Final e Trabalho de Conclusão de Curso', 'MR207', null, 3)
-- curso de 1 ano
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Gestão de Pessoas – Relações Humanas', 'PG101', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Gestão Mercadológica', 'PG102', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Fundamentos de Gestão Empresarial', 'PG103', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Projeto Integrador', 'PG104', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Direito', 'PG105', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Projetos de Pesquisa e Metodologia', 'PG106', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Fundamentos de Finanças', 'PG107', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Gestão de Projetos', 'PG108', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Meio Ambiente e Sociedade – Relações Afro Descendentes', 'PG109', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Fundamentos de Planejamento Estratégico nas organizações', 'PG110', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Ética e Cidadania', 'PG111', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Gestão da Qualidade', 'PG112', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Fundamentos de Estrutura Organizacional', 'PG113', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Empreendedorismo e Inovação', 'PG114', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Empresas Sistêmicas', 'PG201', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Formação de Preços', 'PG202', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Processos e Unidades Estratégicas de Negócios', 'PG203', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Fundamentos Contábeis e Tributários', 'PG204', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Logística Empresarial', 'PG205', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Operações de manufatura e serviços', 'PG206', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Gestão de custos nos processos', 'PG207', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Mapeamento Informatizado de processos', 'PG208', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Consultoria e Negócios', 'PG209', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Políticas de Crédito e Empréstimos', 'PG210', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Tomadas de decisões gerenciais', 'PG211', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('LIBRAS', 'PG212', null, 2)
-- curso de 2 anos
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('CORES E PERCEPÇÃO VISUAL', 'DI101', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('COMPOSIÇÃO E FORMA', 'DI102', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('LÍNGUA BRASILEIRA DE SINAIS', 'DI103', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('SOCIEDADE, IDENTIDADES E TERRITÓRIOS', 'DI104', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('EXPRESSÃO GRÁFICA', 'DI105', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('METODOLOGIA DE PROJETO EM DESIGN', 'DI201', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('HISTÓRIA DAS ARTES', 'DI202', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('PROJETO DE INTERIORES: RESIDENCIAL', 'DI203', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('ITINERÁRIO EXTENSIONISTA I', 'DI204', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('DESENHO TÉCNICO E INFORMÁTICA APLICADA AO DESIGN DE INTERIORES', 'DI205', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('ERGONOMIA', 'DI206', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('CENOGRAFIA', 'DI207', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('TEORIA E HISTÓRIA DA ARTE E DO DESIGN', 'DI301', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('PROJETO DE ARQUITETURA: DIMENSÕES E PROPORÇÕES', 'DI302', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('MATERIAIS E ACABAMENTOS PARA DESIGN DE INTERIORES', 'DI303', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('CONFORTO AMBIENTAL', 'DI304', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('INSTALAÇÕES E EQUIPAMENTOS ELÉTRICOS E HIDRÁULICOS', 'DI305', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('PROJETO DE INTERIORES: COMERCIAL', 'DI306', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('ITINERÁRIO EXTENSIONISTA II', 'DI307', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('ITINERÁRIO EXTENSIONISTA III', 'DI401', null, 4)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('PSICOLOGIA E COMPORTAMENTO DO CONSUMIDOR', 'DI402', null, 4)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('PROJETO DE INTERIORES: INSTITUCIONAL', 'DI403', null, 4)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('PAISAGISMO', 'DI404', null, 4)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('ESTILO E HISTÓRIA DO MOBILIÁRIO', 'DI405', null, 4)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('EMPREENDEDORISMO E INOVAÇÃO', 'DI406', null, 4)
