insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('LIBRAS', 'AV101', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Práticas de Ensino para a Educação Especial numa Perspectiva Inclusiva', 'AV102', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Currículos, didática e Práticas Avaliativas do Ensino e da Aprendizagem', 'AV103', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Política e Organização da Educação no Brasil', 'AV104', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Estudo das Relações Étnico-Raciais para o Ensino de História e Cultura Afro-brasileira, Africana e Indígena', 'AV104', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Psicologia da Educação e Teorias da Aprendizagem', 'AV105', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Estética e Filosofia da Arte', 'AV106', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Fundamentos da Linguagem Visual', 'AV107', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Tecnologias Digitais e Expressões Artísticas Visuais', 'AV108', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('	Arte Conceitual, Instalações e Arte Urbana', 'AV109', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Arte Brasileira na formação da Identidade Nacional', 'AV110', null, 1)

insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Teoria e Fundamentos de Gestão', 'MR101', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Tecnologia da Informação', 'MR102', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Pensamento Critico e Comunicação', 'MR103', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Introdução à Contabilidade', 'MR104', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Matemática Aplicada', 'MR105', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Meio Ambiente e Sustentabilidade', 'MR106' null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Projeto Multidisciplinar – Introdução à Gestão', 'MR107', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Marketing', 'MR108', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Comportamento do Consumidor', 'MR109', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Ambiente Legal de Negócios', 'MR110', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Planejamento de Marketing', 'MR111', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Economia de Empresas', 'MR112', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Gestão de Projetos', 'MR113', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Projeto Multidisciplinar – Marketing', 'MR114', null, 1)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Marketing Digital', 'MR201', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Fundamentos de E-commerce e E-business', 'MR202', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Ética, Cidadania e Responsabilidade Social', 'MR203', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Comunicação em Redes Sociais', 'MR204', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Plataforma de E-commerce', 'MR205', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('História e Cultura Afro-brasileira e Indígena', 'MR206', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Projeto Multidisciplinar – Comércio Eletrônico e Mídias Digitais', 'MR207', null, 2)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Branding', 'MR301', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Publicidade, Propaganda e Design', 'MR302', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Probabilidade e Estatística', 'MR303', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Estratégias de Marketing', 'MR304', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Planejamento Estratégico de Vendas', 'MR305', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Empreendedorismo', 'MR306', null, 3)
insert into DISCIPLINA(nome, codigo, id_departamento, semestre) values ('Projeto Multidisciplinar Final e Trabalho de Conclusão de Curso', 'MR207', null, 3)

