insert into faculdade.professor (nome, id_departamento, id_prof) values ('Glennis Cosens', 01, '7358');
insert into faculdade.professor (nome, id_departamento, id_prof) values ('Quinn Labitt', 02, '3023');
insert into faculdade.professor (nome, id_departamento, id_prof) values ('Wrennie Sealy', 02, '4568');
insert into faculdade.professor (nome, id_departamento, id_prof) values ('Guillermo Le Galle', 03, '0673');
insert into faculdade.professor (nome, id_departamento, id_prof) values ('Lucia Eaglesham', 04, '3677');
insert into faculdade.professor (nome, id_departamento, id_prof) values ('Billy Macconaghy', 05, '0793');
insert into faculdade.professor (nome, id_departamento, id_prof) values ('Bellina McGarahan', 05, '9711');
insert into faculdade.professor (nome, id_departamento, id_prof) values ('Dee Wallach', 06, '3477');
insert into faculdade.professor (nome, id_departamento, id_prof) values ('Jannelle Loines', 04, '4481');
insert into faculdade.professor (nome, id_departamento, id_prof) values ('Bar Britner', 07, '5275');
insert into faculdade.professor (nome, id_departamento, id_prof) values ('Pedro Souza', 03, '9852');
