insert into faculdade.tcc (id_tcc, id_prof, titulo) values (3094, 7358, 'ipsum primis');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (5380, 3677, 'eget eros elementum');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (5451, 5275, 'tellus nisi eu');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (9171, 7358, 'habitasse platea dictumst');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (6334, 3677, 'ante nulla justo aliquam');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (2767, 3677, 'ac nibh fusce lacus');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (7372, 7358, 'ac diam');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (1107, 4481, 'sed ante');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (4251, 4481, 'justo eu massa donec');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (1544, 5275, 'rhoncus dui vel');

insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('7977', '4481', 'vivamus vestibulum sagittis sapien');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('2766', '3477', 'cubilia curae');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('2996', '9852', 'diam cras pellentesque volutpat');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('4085', '3477', 'pede posuere');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('7193', '1673', 'dapibus nulla suscipit ligula');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('1846', '9852', 'in imperdiet et');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('4594', '1673', 'augue vestibulum ante');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('4639', '7358', 'ultricies eu');

insert into faculdade.tcc (id_tcc, id_prof, titulo) values (7262, '3677', 'ut massa');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (2989, '3023', 'vel accumsan tellus nisi');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (1611, '7358', 'enim in tempor turpis');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (2973, '4481', 'erat quisque erat eros');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (1030, '3677', 'nisl duis bibendum');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (5178, '7358', 'sapien dignissim vestibulum');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (7937, '3677', 'in ante vestibulum');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (8344, '7358', 'eros viverra eget congue');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (7630, '4568', 'turpis sed');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (5547, '3677', 'pede lobortis ligula');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (3993, '3477', 'id sapien');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (8743, '9852', 'curabitur convallis duis');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (1208, '3477', 'felis sed interdum venenatis');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (1572, '9852', 'lacus at velit');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (5049, '7358', 'et tempus');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (3490, '1673', 'et eros vestibulum ac');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (4490, '1673', 'fringilla rhoncus mauris enim');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values (2210, '9852', 'in tempus sit');

insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('2283', '4481', 'felis sed interdum venenatis');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('6476', '1793', 'porttitor pede');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('9118', '7358', 'quam turpis');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('8143', '9711', 'hac habitasse platea');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('2773', '5275', 'luctus cum sociis');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('9758', '1793', 'odio cras mi pede');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('1773', '4481', 'eleifend pede');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('6327', '4481', 'eu pede');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('1183', '1793', 'in leo');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('3751', '1673', 'in lacus');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('5447', '1673', 'sit amet sem fusce');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('5323', '4481', 'sagittis dui');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('1962', '5275', 'mauris eget');
insert into faculdade.tcc (id_tcc, id_prof, titulo) values ('1178', '9852', 'interdum mauris ullamcorper');
